project_id = "gifbpcouqzjsesvpqbto"

[functions.generate-player-portrait]
verify_jwt = false

[functions.analyze-dartboard]
verify_jwt = false

[functions.send-push]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false
