
ALTER TABLE public.players
  ADD COLUMN IF NOT EXISTS bio TEXT,
  ADD COLUMN IF NOT EXISTS throwing_hand TEXT,
  ADD COLUMN IF NOT EXISTS dart_weight_g INTEGER,
  ADD COLUMN IF NOT EXISTS favorite_double TEXT,
  ADD COLUMN IF NOT EXISTS hometown TEXT,
  ADD COLUMN IF NOT EXISTS joined_year INTEGER,
  ADD COLUMN IF NOT EXISTS motto TEXT,
  ADD COLUMN IF NOT EXISTS birthday DATE;
