-- KI-Spielbericht (AI match recap) — a short, punchy sports-journalist-style recap generated by
-- the new generate-match-report edge function from a finished match's own real stats (average,
-- highest visit, checkout rate, legs/sets won), shown on the post-game screen and folded into the
-- existing PNG share card. Opt-in: a player taps "KI-Spielbericht generieren" on the winner
-- overlay; nothing is generated automatically for every match.
--
-- Deliberately NO new UPDATE policy on public.games for this column. `games` already has no
-- authenticated-UPDATE policy at all (games_played/average/etc. are written exclusively by the
-- apply_game_player_stats() SECURITY DEFINER RPC — see 20260823140000_server_side_player_stat_
-- rollup.sql's own comment on why a plain client UPDATE is rejected by design). ai_report follows
-- that same convention: the edge function writes it via the service role, only after using the
-- CALLING user's own JWT to SELECT the row first — which already enforces "only for a game this
-- user's club can see" via the existing "Members can view all club games" policy. Reading it back
-- needs no new policy either, since that SELECT policy already covers every column including this
-- new one.
alter table public.games add column if not exists ai_report text;

comment on column public.games.ai_report is
  'AI-generated post-match recap (KI-Spielbericht), written by the generate-match-report edge function via the service role. Null until a player opts in by tapping "KI-Spielbericht generieren" on the post-game screen.';
